services:
  api:
    image: ghcr.io/arinji2/garconia-api:latest
    container_name: garconia-api
    volumes:
      - ./db:/db
    env_file:
      - ./api/.env
    networks:
      - app-network
      - proxy
    restart: unless-stopped

  bot:
    image: ghcr.io/arinji2/garconia-law-bot:latest
    container_name: garconia-law-bot
    env_file:
      - ./bot/.env
    depends_on:
      - pocketbase
    networks:
      - app-network
      - proxy
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.24.4
    container_name: garconia-pb
    volumes:
      - ./pb_data:/pb_data
    networks:
      - app-network
      - proxy
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  proxy:
    external: true

