CREATE TABLE signups (
    id VARCHAR(10) PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    verified BOOLEAN DEFAULT 0,
    sent BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE verifications (
    id VARCHAR(10) PRIMARY KEY,
    user_id VARCHAR(10) NOT NULL,
    resend_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES signups(id) ON DELETE CASCADE
)
