CREATE TABLE signups (
    id VARCHAR(10) PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    verified BOOLEAN DEFAULT 0,
    sent BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
